### ISSUE TITLE
Update to v4.2.1

### ISSUE THREAD

**Issue by mehdicopter** [gehaxelt/PHP-Easy-PGP-Composer#1]
Hello,
Is it possible to update openpgp.js to the last version ?

**Comment by gehaxelt** [comment]
@mehdicopter Just created a PR which uses the latest OpenPGP.js release. 

Do you mind testing and approving it?

**Comment by mehdicopter** [comment]
Yeah I tried and it works. Thanks a lot !
I'll use your work to help me create a contact form using latest openpgpjs and bootstrap.
Great work thanks again !
